In [1]:
import numpy as np
print (np.__version__)

1.24.3


NumPy (Numerical Python) is one of the most fundamental and widely-used libraries in Python for numerical computing. It provides powerful data structures, tools, and functions for performing mathematical operations on large, multi-dimensional arrays and matrices.

NumPy is an essential library for numerical and scientific computing in Python. It provides an efficient way to handle large datasets, perform complex mathematical operations, and interface with other scientific libraries.

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Use a tuple to create an nd array

In [3]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2D array

In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [11]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
d = np.array(42)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
0


# Accessing Array Elements

In [12]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1]) #here 1,2,3,4 is oth row and 5,6,7,8 is 1st row inside that position of element
print(arr[1,3])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[1, 2])  # Output: 6 (second row, third column)

2
8
6


In [94]:
import numpy as np
arr = np.array([[[1,3,4],[5,6,7]],[[8,9,10],[11,12,13]]])
print(f"Dimension is : {arr.ndim}")
print(arr[0,1,2])
print(arr[1,0,2])
arr1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(f"Dimension is : {arr1.ndim}")
print(arr1[1,1,1])
print(arr1[1,2,0])
print(arr1[1,2,-2])
print(arr1[1,1,-1])

Dimension is : 3
7
10
Dimension is : 3
14
16
17
15


# Slicing in Arrays

# Slicing of 1D Array

In [39]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print([arr[1:5]])

[array([2, 3, 4, 5])]


In [52]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
#Slices the array starting at index 1 up to (but not including) index 5.
#This returns the elements at indices [1, 2, 3, 4] (i.e., [2, 3, 4, 5]).

print(arr[4:])
#Slices the array starting from index 4 and goes until the end

print(arr[:4])
#Slices the array from the beginning (index 0) up to (but not including) index 4.

print(arr[-3:-5])

#This is using negative indexing, where:
#-3 refers to the 3rd element from the end of the array (which is 5).
#-5 refers to the 5th element from the end of the array (which is 3).
#Since the start index (-3) is greater than the end index (-5), this will return an empty array because the slice direction is reversed.

print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[]
[5 6]


# Slicing of 2D array

In [67]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])
print(arr[0,3:5])
print(arr[1:,2:])

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(f"Dimension is : {arr1.ndim}")
print(arr1[2::2,::2])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
[4 5]
[[ 8  9 10]]
Dimension is : 2
[[11 13 15]]


2::2 (row slicing):

Start at index 2 (third row, which is [11, 12, 13, 14, 15]).
Use a step of 2, which means selecting every second row starting from index 2. So, this will pick rows at index 2 and 4 (but since arr1 only has 4 rows, it only picks row 2).
Therefore, it selects the third row: [11, 12, 13, 14, 15].
::2 (column slicing):

This selects every second column from the selected rows, starting from the first column (index 0).
So, from [11, 12, 13, 14, 15], it selects columns at indices 0, 2, 4, which gives [11, 13, 15].

# Notes

1) You access elements using row index and column index. The syntax is arr[row, column].

Example:  print(arr_2d[0, 1]) Accesses the element in the first row and second column.

2) You can slice a 2D array to select specific rows and columns. The slicing syntax is arr[start_row:end_row, start_col:end_col].


3) In a 3D array, you access elements using three indices: arr[block, row, column].

Example: print(arr_3d[1, 0, 2])  # Accesses the second block, first row, third column

4) You can slice a 3D array in a similar way to a 2D array, but with an extra index for the "depth" (blocks). The syntax is arr[start_block:end_block, start_row:end_row, start_col:end_col].

print(arr_3d[0:, 1:, 1:])  # Selects all blocks, starting from the second row and second column


# Dataypes in Numpy

In [69]:
import numpy as np
arr = np.array(['apple','banana'])
arr1 = np.array([1,2,3,4])
print(arr1.dtype)
print(arr.dtype)

int32
<U6


In [78]:
import numpy as np
arr = np.array([1,2,3,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [80]:
import numpy as np
arr = np.array([1,22,3222,4],dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'22' b'3222' b'4']
|S4


Array Creation with dtype='S':

dtype='S' means that each element of the array will be stored as a byte string.
The size of each string is determined by the length of the string when it's converted to a byte.

The | denotes the byte-order, which is platform-dependent (for most systems, it's little-endian).
S1 means that each string is 1 byte in length.

In [81]:
import numpy as np
arr = np.array([1,2,3,4],dtype = 'U')
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


Here, each element is a regular string, and the dtype='U1' indicates that each element is a Unicode string of length 1.

In [82]:
import numpy as np
arr = np.array([1,222,3,4],dtype = 'U')
print(arr)
print(arr.dtype)

['1' '222' '3' '4']
<U3


# astype()

In [84]:
arr = np.array([1.1,2.1,3.1,4.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


1) The astype() method is used to cast (convert) the array to a different data type.
2) 'i' in astype('i') specifies that you want to convert the array to an integer type. In NumPy, 'i' typically represents a signed integer (int32 or int64, depending on your system).

# Copy and View 

In [85]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [86]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [88]:
import numpy as np

# Create an original array
arr = np.array([1, 2, 3, 4, 5])

# Create a view of the original array
view_arr = arr[1:4]
print(view_arr)
# Modify the view
view_arr[0] = 99

print("Original Array:", arr)  # The original array is affected
print("View Array:", view_arr)


[2 3 4]
Original Array: [ 1 99  3  4  5]
View Array: [99  3  4]


In [89]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
y= arr.copy()
print(x.base)
print(y.base)

[1 2 3 4 5]
None


# Numpy Array Shape

In [97]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [102]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [113]:
import numpy as np

arr = np.array([1, 2, 3, 4])
reshaped_arr = arr.reshape((1, 1, 1, 1, 4))
print(reshaped_arr)
print(reshaped_arr.ndim)
print(reshaped_arr.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


In [115]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Here 2 outer array inside that 3 inner array and 2 elements inside that

In [110]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape accepts 2 args means it is a 2d array

In [116]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


If we dont know exact dimension in reshape method pass -1 numpy will calculate this number for u.

# Flattening of arrays

Converting multidimensional array to 1D array is called flattening. reshape(-1) is used to flatten the array

In [117]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Numpy Array Iterating

# Iterating 1D array

In [118]:
import numpy as np
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


# Iterating 2D array

In [119]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


To get the scalar value add one more loop to iterate array in each dimension

In [120]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


# Iterating 3D array

In [121]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To get the scalar value iterate array in each dimension

In [122]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterate array using nditer()

In [123]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating array with different datatypes

In [132]:
import numpy as np

arr = np.array([1, 2, 3, 4])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)


b'1'
b'2'
b'3'
b'4'


# Iterating with different step size

In [137]:
arr = np.array([[1,2,3],[5,6,7]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [138]:
arr = np.array([[1,2,3],[5,6,7]])
for x in np.nditer(arr[0,::2]):
    print(x)

1
3


# Enumerated iteration using ndenumerate

In [140]:
import numpy as np
arr = np.array([1,2,3])
for index, value in np.ndenumerate(arr):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3


The np.ndenumerate() function in NumPy is a great way to iterate over each element in a multidimensional array along with their indices.

# ndenumerate on 2 D array

In [141]:
import numpy as np

# Create a 2x2 array
arr = np.array([[1, 2], [3, 4]])

# Enumerate over the array
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4


# Numpy Joining Array

# Using Concatenate Function

In [143]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


axis is not specified means its stacked vertically

In [144]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


The np.concatenate function combines arr1 and arr2 along the specified axis. Here, axis=1 means the arrays are concatenated horizontally, i.e., along the columns

# Joining arrays using stack functions

In [90]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[7,8,9]])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]


In [96]:
import numpy as np
arr1 = np.array([[1,2,3],[41,53,64]])
arr2 = np.array([[4,5,6],[7,8,9]])
arr = np.dstack((arr1,arr2))
print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[41  7]
  [53  8]
  [64  9]]]


In [155]:
import numpy as np
arr1 = np.array([[1,2,3],[41,53,64]])
arr2 = np.array([[4,5,6],[7,8,9]])
arr = np.hstack((arr1,arr2))
print(arr)

[[ 1  2  3  4  5  6]
 [41 53 64  7  8  9]]


In [152]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.stack((arr1,arr2),axis =1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [156]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.vstack((arr1,arr2))
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [157]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.hstack((arr1,arr2))
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8]
1


In [95]:
import numpy as np
arr1 =np.array([[[1,3,4],[5,6,7]],[[8,9,10],[11,12,13]]])
arr2 =arr = np.array([[[14,34,44],[54,64,75]],[[86,97,10],[14,17,34]]])
arr = np.dstack((arr1,arr2))
print(arr)

[[[ 1  3  4 14 34 44]
  [ 5  6  7 54 64 75]]

 [[ 8  9 10 86 97 10]
  [11 12 13 14 17 34]]]


# Numpy Splitting Arrays

In [168]:
import numpy as np
arr= np.array([1,2,3,4,5,])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


we use array_split() for splitting arrays. If the array has less elements than required it will adjust from end accordingly

In [169]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [171]:
import numpy as np
arr= np.array([1,2,3,4,5,])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5]


In [174]:
import numpy as np
arr =np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [177]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[17,18,19]])
newarr = np.array_split(arr,3,axis=0)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [17, 18, 19]])]


In [178]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[17,18,19]])
newarr = np.array_split(arr,3,axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [17]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [18]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [19]])]


# hsplit() vsplit() dsplit()

In [160]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13,
14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [161]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13,
14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [166]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)
newarr = np.dsplit(arr, 3)

print(newarr)

(2, 2, 3)
[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])]


In [181]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13,
14, 15], [16, 17, 18]])
newarr = np.dsplit(arr, 3)
print(newarr)

ValueError: dsplit only works on arrays of 3 or more dimensions

See the above exasmple dsplit only works in an 3D arrays

# Numpy searching arrays

we can search for a ceratin value in an array and return the indexes that get a match. To search an array use where() method

In [179]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(arr % 2 == 0)
y = np.where(arr % 2 == 1)
print(x)
print(y)

(array([1, 3, 5, 7, 9], dtype=int64),)
(array([0, 2, 4, 6, 8], dtype=int64),)


# Search sorted

In [189]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


searchsorted will return the index position of element we are searching

In [250]:
import numpy as np
x = np.array([10, 4, 11, 13, 6, 20])
4,5,6,10,11,20
index = np.searchsorted(x, 12)
print(index)

3


In [251]:
import numpy as np
x = np.array([10, 4, 11, 5, 6, 20])
4,5,6,10,11,20
index = np.searchsorted(x, 1, side='right')
print(index) #check the next element if its large consider next position. like that it goes

0


In [209]:
import numpy as np
x = np.array([4,5,6,7,10,11,20])
index = np.searchsorted(x, 12, side='left')
print(index)
print(x)

6
[ 4  5  6  7 10 11 20]


In [219]:
arr =np.array([6,7,8,9])
x = np.searchsorted(arr,7,side='left')
print(x)

1


In [216]:
arr =np.array([6,7,8,9])
x = np.searchsorted(arr,7,side='right')
print(x)

2


The np.searchsorted function finds the index where the value 7 should be inserted to maintain order. The side='right' parameter specifies that the insertion should be to the right of any existing entries of 7.

In [222]:
arr =np.array([5,6,7,8,9])
x = np.searchsorted(arr,5,side='right')
print(x)

1


In [228]:
import numpy as np
arr= np.array([1,3,5,7])
x =np.searchsorted(arr,[3,4,6])
print(x)

[1 2 3]


# Numpy sorting arrays

In [229]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [230]:
arr = np.array(['banana','apple','cherry'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [231]:
arr = np.sort([True,False,True])
print(np.sort(arr))

[False  True  True]


# Sorting a 2D array

In [232]:
arr =np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Numpy Filter Array

In [233]:
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[41 43]


In [235]:
import numpy as np
arr = np.array([41,42,43,44])
filter_arr = []
for element in arr:
    
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [236]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_arr = []
for element in arr:
    
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [238]:
import numpy as np
arr = np.array([41,42,43,44])
filter_arr = arr> 42
newarr = arr[filter_arr]
#print(filter_arr)
print(newarr)

[43 44]


# Generate random number and array 

In [260]:
from numpy import random
x = random.randint(100)
print('x is :', x)
y = random.rand()
print('y is :', y)
z = random.randint(100,size = (5))
print('z is ',z)
a = random.randint(100,size=(3,5))
print('a is:',a)
b = random.rand(5)
print('b is:', b)
c = random.rand(3,5)
print('c is:',c) 

x is : 83
y is : 0.1685743325620126
z is  [89 40 26 35  0]
a is: [[37 77 93 58 99]
 [ 5  2 85 50 36]
 [14 85 97 24  2]]
b is: [0.40618388 0.18908484 0.60152694 0.05755579 0.07308377]
c is: [[0.84667687 0.19045145 0.69481348 0.12222508 0.26414008]
 [0.51029034 0.53709251 0.99236727 0.83048467 0.77260121]
 [0.5248696  0.13757438 0.45038073 0.88332029 0.1900831 ]]


# Choice method

In [269]:
randval = random.choice([3,5,7,9])
print("Random value is ",randval)
randval2 = random.choice([3,5,7,9],size = (3,5))
print('Random 2D array is:', randval2)

randval3  = random.choice([3,5,7,9],p = [0.1,0.3,0.6,0.0],size=100)
print("1D array with defined probability is:",randval3)

randval4 = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print("2D array with defined probability is:", randval4)



Random value is  5
Random 2D array is: [[7 7 5 5 9]
 [5 3 7 3 5]
 [9 9 7 7 3]]
1D array with defined probability is: [5 5 5 5 7 5 3 7 5 5 5 3 5 7 7 5 5 7 5 5 5 5 7 3 7 3 3 5 7 7 5 7 7 7 7 5 7
 7 7 5 7 5 7 5 7 5 5 5 7 7 7 5 5 7 7 5 5 7 7 5 7 7 7 5 5 5 7 5 3 5 7 7 7 5
 7 7 3 7 7 5 7 3 7 7 7 5 7 3 7 5 7 7 7 7 7 3 5 7 7 5]
2D array with defined probability is: [[5 5 5 7 7]
 [5 7 5 7 3]
 [7 7 7 7 7]]


# Shuffling and Permutation

In [273]:
arr = np.array([1,2,3,4,5])
arr2 = random.shuffle(arr)
print("The input array is :", arr)
print("Array after applying shuffle function is ",arr2)
arr1 = [5,6,8,23,56]
newarr1 = random.permutation(arr1)
print("The input array is ",arr1)
print("Array after applying permuatation function is ",newarr1)

The input array is : [2 3 4 1 5]
Array after applying shuffle function is  None
The input array is  [5, 6, 8, 23, 56]
Array after applying permuatation function is  [ 8  5 23 56  6]


1) Using random.shuffle:
random.shuffle shuffles the array in place and returns None.
Therefore, arr2 will be None.

2) Using random.permutation from NumPy:
random.permutation is not a function in the random module but in NumPy. It returns a new array with the elements permuted.